# Generated by Django 2.0 on 2019-10-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SsoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('metadata_file', models.FileField(blank=True, null=True, upload_to='uploads/meta')),
                ('metadata_url', models.CharField(blank=True, max_length=1000)),
                ('entity_id', models.CharField(blank=True, max_length=1000)),
                ('acs', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
